### ISSUE TITLE
feature: sort according to pertinence

### ISSUE THREAD

**Issue by Konfekt** [pbrisbin/mail-query#5]
For quicker access, sort matches by pertinence, as done crudely at

https://github.com/Konfekt/vim-mailquery/blob/ca7da206d1bb2435bd314a4ce493ead501ca0301/autoload/mailquery.vim#L135

The more often the sought-for pattern is matched at the beginning or after a delimiter in the name respectively e-mail address, the more pertinent it is.

**Comment by pbrisbin** [comment]
Sounds like a great feature.

I actually no longer use this project (and am not a C developer, this was mostly an exercise for me). Would you interested in taking over as maintainer? I would make you a collaborator on this repo and you could take it from there.

**Comment by Konfekt** [comment]
Sure, I'd be glad to help. This would also be a useful exercise for me (which might take a while, though).
