### ISSUE TITLE
Make install error 64

### ISSUE THREAD

**Issue by chunkhang** [pbrisbin/mail-query#6]
Just putting this here, in case anyone else encounters this error when trying to do `sudo make install` on MacOS:

```
install -D -m755 mail-query /usr/local/bin/mail-query
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

Just remove the `-D` option from `Makefile`.

```
install: all
	install -m755 $(OUT) $(DESTDIR)$(PREFIX)/bin/$(OUT)
```

**Comment by pbrisbin** [comment]
Thanks for reporting this. The `-D` is meant to create leading directories if necessary. By default the install path is just `/bin`, so it wouldn't matter, but this functionality be may necessary if you set a `DESTINATION` or `PREFIX`. So we may want to consider some alternatives to just removing it:

- Make a Homebrew recipe for OSX and don't consider the `Makefile` as supported there
- Indeed remove `-D`, but add `mkdir -p`
- Indeed just remove `-D`, and hope the error is clear and the user can `mkdir -p` things themselves

The last option is attractive to a minimalist, but it may not be possible if you're in a package-building scenario (e.g. an Arch `PKGBUILD`) where you're installing files into a package file-tree that you can't modify before the `make` happens.

The first option is ideal, but I don't really use or maintain this package as it is, and as a Linux user, I _really_ wouldn't be best suited to maintaining the Homebrew recipe.

**Comment by chunkhang** [comment]
Hmm, I think the error would be clear in the case that `mkdir -p` is needed. Thanks for clarifying!
